[uwsgi]
chdir = .
module = wsgi:app

master = true
processes = 2
threads = 2

http = 0.0.0.0:8001
vacuum = true
die-on-term = true
single-interpreter = true
enable-threads = true

harakiri = 60
max-requests = 1000
